#!/usr/bin/env bash
# Fetch/build the Android native dependencies into the gen/android jniLibs:
#   - xray-core (Android arm64) -> libxray.so   (exec'd from nativeLibraryDir)
#   - hev-socks5-tunnel (tun2socks) -> libhev-socks5-tunnel.so
# These are large/binary, so they're gitignored and (re)generated by this
# script. Requires the Android NDK (ANDROID_NDK_HOME / NDK_HOME). Run from the
# project root.
set -euo pipefail

XRAY_VER="26.6.27"
ABI="arm64-v8a"
# hev-socks5-tunnel ships an Android JNI in src/hev-jni.c that registers
# TProxyStartService/TProxyStopService onto <PKGNAME>/TProxyService. Build with
# our package so app.varmlen.client.TProxyService binds to it.
PKGNAME="app/varmlen/client"
ROOT="$(pwd)"
JNI="$ROOT/src-tauri/gen/android/app/src/main/jniLibs/$ABI"
NDK="${ANDROID_NDK_HOME:-${NDK_HOME:-}}"

mkdir -p "$JNI"

# --- xray (Android arm64) ---
if [ ! -f "$JNI/libxray.so" ]; then
  echo "fetching xray-core $XRAY_VER (android arm64)…"
  TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
  curl -fsSL -o "$TMP/x.zip" \
    "https://github.com/XTLS/Xray-core/releases/download/v${XRAY_VER}/Xray-android-arm64-v8a.zip"
  unzip -o -q "$TMP/x.zip" xray -d "$TMP"
  install -m 0755 "$TMP/xray" "$JNI/libxray.so"
fi

# --- hev-socks5-tunnel (tun2socks) with built-in JNI ---
if [ ! -f "$JNI/libhev-socks5-tunnel.so" ]; then
  [ -n "$NDK" ] || { echo "set ANDROID_NDK_HOME or NDK_HOME"; exit 1; }
  echo "building hev-socks5-tunnel (tun2socks, JNI PKGNAME=$PKGNAME)…"
  T2S="$(mktemp -d)"
  git clone --recursive --depth 1 https://github.com/heiher/hev-socks5-tunnel \
    "$T2S/hev-socks5-tunnel"
  mkdir -p "$T2S/jni"
  ln -s "$T2S/hev-socks5-tunnel" "$T2S/jni/hev-socks5-tunnel"
  echo 'include $(call all-subdir-makefiles)' > "$T2S/jni/Android.mk"
  ( cd "$T2S" && "$NDK/ndk-build" NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=jni/Android.mk \
      APP_ABI="$ABI" APP_PLATFORM=android-24 \
      APP_CFLAGS="-O3 -DPKGNAME=$PKGNAME" \
      APP_LDFLAGS="-Wl,--build-id=none -Wl,--hash-style=gnu" -j4 )
  install -m 0644 "$T2S/libs/$ABI/libhev-socks5-tunnel.so" "$JNI/libhev-socks5-tunnel.so"
  rm -rf "$T2S"
fi

echo "android native libs ready in $JNI"
